In [1]:
import numpy as np

In [2]:
#1. Create a null vector of size 10 but the fifth value which is 1.
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
#2. Create a vector with values ranging from 10 to 49.
b=np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
c=np.arange(0,9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
d=np.array([1,2,0,0,4,0])
print(d.nonzero())

(array([0, 1, 4], dtype=int64),)


In [6]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
np.random.seed(4)
e=np.random.randint(1,101,(10,10))
print(e.max())
print(e.min())

99
1


In [7]:
#6. Create a random vector of size 30 and find the mean value.
np.random.seed(1)
f=np.random.randint(1,10,(5,6))
print(round(f.mean(),3))
#print("Mean=%.3f"%f.mean())

5.167
